# This is a basic workflow that is manually triggered

name: Update Domains

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: ["master"]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.16"
          
      - name: Build
        run: yarn && yarn build
        
      - name: Generate
        run: yarn --silent generate > domains.json && cat domains.json
        
      - name: Upload to s3
        run: aws --version 
